name: ebn_balady
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  font_awesome_flutter: ^10.2.1
  flutter_icons: ^1.1.0
  material_design_icons_flutter: ^5.0.6996
  get: ^4.6.5
  flutter_svg: ^1.1.5
  concentric_transition: ^1.0.3
  lottie: ^1.4.2
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  flutter_native_splash: ^2.2.9
  cached_network_image: ^3.2.1
  hive: ^2.2.3
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  country_picker: ^2.0.17
  animated_theme_switcher: ^2.0.5
  flutter_spinkit: ^5.1.0
  permission_handler: ^10.0.2
  mobile_scanner: ^2.0.0
  flushbar: ^1.10.4
  logger: ^1.1.0
  contacts_service: ^0.6.3
  another_flushbar: ^1.12.29
  awesome_dialog: ^3.0.2
  flutter_zoom_drawer: ^3.0.3
  flutter_dialogs: ^3.0.0
  flutter_image_stack: ^0.0.6
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  anim_search_bar: ^2.0.2
  dropdown_button2: ^1.8.2
  expandable: ^5.0.1
  flutter_inset_box_shadow: ^1.0.8
  dropdown_search: ^5.0.3
  percent_indicator: ^4.2.2
  firebase_core: ^1.24.0
  google_maps_flutter: ^2.2.1
  flutter_advanced_segment: ^3.0.1
  email_validator: ^2.1.17
  phone_number: ^1.0.0
  flutter_pw_validator: ^1.4.2
  flutter_local_notifications: ^12.0.2
  rxdart: ^0.27.5
  fluttertoast: ^8.1.1
  oauth_dio: ^0.2.7
  hive_flutter: ^1.1.0
  firebase_messaging: ^13.1.0
  firebase_auth: ^3.11.2
  firebase_remote_config: ^2.0.20
  firebase_crashlytics: ^2.9.0
  device_info_plus: ^8.0.0
  flutter_secure_storage: ^6.0.0
  package_info_plus: ^1.4.2
  pin_code_fields: ^7.4.0
  lazy_load_scrollview: ^1.3.0
  timeago: ^3.3.0
  url_launcher: ^6.1.6
  local_auth: ^2.1.2
  flutter_toggle_tab: ^1.2.0
  avatar_glow: ^2.0.2
  share: ^2.0.4
  path: ^1.8.1
  flutter_polyline_points: ^1.0.0
  shimmer: ^2.0.0
  argon_buttons_flutter: ^1.1.0
  new_version: ^0.2.3
  flutter_validation:
    git:
      url: https://github.com/MoaidAlrazhy/flutter_validation.git
      ref: 1.0.6
  location: ^4.4.0
  clip:
    git:
      url: https://github.com/MoaidAlrazhy/dart-clip.git
      ref: 1.1.7
  feature_discovery:
    git:
      url: https://github.com/MoaidAlrazhy/feature_discovery.git
      ref: f23da9e
  flutter_jailbreak_detection: ^1.8.0
  flutter_riverpod: ^1.0.4
  infinite_scroll_pagination: ^3.2.0
  video_player: ^2.4.7
  chewie: ^1.3.5
  record: ^4.4.3
  animated_text_kit: ^4.2.2
  just_audio: ^0.9.30
  bubble: ^1.2.1
  flutter_linkify: ^5.0.2
  linkify: ^4.1.0
  visibility_detector: ^0.3.3
  regex_router: ^2.0.0
  material_dialogs: ^1.1.3
  scroll_date_picker: ^3.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.1
  bloc_test: ^9.1.0
  test: ^1.21.1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  hive_generator: ^1.1.3

flutter_native_splash:
  color: "#438099"
  image: assets/images/icons/logo_white.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  fonts:
    - family: Baloo_Bhaijaan_2
      fonts:
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Baloo_Bhaijaan_2/BalooBhaijaan2-SemiBold.ttf
          weight: 600

  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/lottie_animations/

